version: '3.8'

services:
  # php 7.4 container
  backend:
    container_name: dddLaravel-php74
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - user=laravel
        - uid=1000
    ports:
      - 81:5000
    networks:
      - ddd-laravel
    volumes:
      - ./:/app

  # mySQL 8 container
  db:
    image: 'mysql/mysql-server:8.0'
    container_name: dddLaravel-mysql
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - './docker-compose/mysql:/var/lib/mysql'
    networks:
      - ddd-laravel
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  # frontend:
  #   image: node:15-alpine
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www
  #     - /var/www/node_modules
  #   command: sh /var/www/docker-compose/node_start.sh
  #   depends_on:
  #     - backend

networks:
  ddd-laravel:
    driver: bridge
